# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ab7b976063c6e37af71bd888a972cf0352d6dac3297e9d537382fb636a5b34b91cfea2f8e04a40a6ba003c0e57daff06f1c0ff3060f5ac3b799d7897f5dfcf9

test:
  secret_key_base: 07f13644fd369bba7084effaf58dfcd8744b2d2bc676eb2b4cf51bf1255aff77a008b6d3fd2bfe5c1f31198997450b185b97a9097b866bc22e1a56bf9bc48910

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
